mqtt:
  broker: localhost
  #port: 8883
  port: 1883
  client_id: screen
  keepalive: 60
  username: mqtt
  password: mqtt
  #certificate: /etc/ssl/certs/DST_Root_CA_X3.pem
  topic: anzeigetafel/#

#RGBMatrix:
#  led-rows: 32
#  led-chain: 2
#  led-parallel: 1
#  led-pwm-bits: 11
#  led-brightness: 100
#  led-gpio-mapping: adafruit-hat-pwm
#  led-scan-mode: 1
#  led-pwm-lsb-nanoseconds: 130
#  led-show-refresh: false
#  led-slowdown-gpio: 0
#  led-no-hardware-pulse: false
DummyMatrix:

sprites: 
    dynLine1:
        type: DynamicFancyText
        data_label: line1
        value_color: red
        font_name: 6x13.bdf
    dynLine2:
        type: DynamicFancyText
        data_label: line2
        font_name: 10x20.bdf
    dynLine3:
        type: DynamicFancyText
        data_label: line3
        font_name: 10x20.bdf
    dynLine4:
        type: DynamicFancyText
        data_label: line4
        font_name: 6x12.bdf
        value_color: blue
    dynLine5:
        type: DynamicFancyText
        data_label: line5
        font_name: 6x12.bdf
        value_color: blue
    scu_logo:
        type: Image
        path: /home/remo/Bilder/SCU-LOGO.jpg
    altherr_logo:
        type: Image
        path: /home/remo/Bilder/altherrLogo.png
    ossv_logo:
        type: Image
        path: /home/remo/Bilder/OSSVLogo.png
    applause:
        type: AnimatedGif
        path: /home/remo/Bilder/applaus.gif
scenes:
    applause:
        sprites:
        - applause:
    scu_logo:
        sprites:
        - scu_logo:
    altherr_logo:
        sprites:
        - altherr_logo:
    ossv_logo:
        sprites:
        - ossv_logo:
    welcome:
        type: Welcome
    time: 
        type: Time
    timing: 
        sprites:
        - dynLine1:
            x: 3
            y: 10
        - dynLine2:
            x: 0
            y: 26
        - dynLine3:
            x: 0
            y: 42
        - dynLine4:
            x: 0
            y: 54
        - dynLine5:
            x: 0
            y: 63
modes: 
    applause:
    - applause:
        brightness: 70
        duration: 500  
    welcome:
    - welcome:
        brightness: 70
        duration: 500   
    time: 
    - time:
        brightness: 70
        duration: 500
    logo:
    - scu_logo:
        brightness: 70
        duration: 10
    - altherr_logo:
        brightness: 70
        duration: 10 
    - ossv_logo:
        brightness: 70
        duration: 10 
    - applause:
        brightness: 70
        duration: 10 
    - timing:
        brightness: 70
        duration: 500 

global:
    font_dir: /home/remo/rpi-rgb-led-matrix/fonts
    default_mode: timing

