version: "3.9"

version: '2'
#Volume definitions
volumes:
  nodered-data:
#Definition of the services
services:
  mqtt:
    restart: always
    container_name: "mqtt"
    image: eclipse-mosquitto
    user: "1000"
    ports:
      - 1883:1883
    volumes:
      - /data/mosquitto/config:/mosquitto/config
      - /data/mosquitto/data:/mosquitto/data
      - /data/mosquitto/log:/mosquitto/log